version: '3.9'
networks:
  web_network:
    name: react_layout_network
    driver: bridge
services:
  reactapp_dev:
    image: react_layout:dev
    build:
      context: ./app/
      dockerfile: Dockerfile.dev
    container_name: reactapp_dev
    restart: always
    volumes:
      - ./app:/usr/app
      - /usr/app/node_modules
    ports:
      - 5173:5173
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - web_network