version: '3.9'
services:
  reactapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reactapp
    restart: always
    volumes:
      - ./:/usr/app
      - /usr/app/node_modules
    ports:
      - 3000:3000

