version: '3.9'

# Network
networks:
  web_network:
    name: react_mui_strapi_network
    driver: bridge

# Services
services:

  # React App Development
  react_dev:
    build: 
      context: ./reactapp
      dockerfile: Dockerfile.dev
    container_name: reactmui_dev
    restart: always
    volumes:
      - ./reactapp:/usr/app
      - /usr/app/node_modules  # Bookmarks Volume
    ports:
      - 5173:5173
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - web_network

  # React App Production
  react_prod:
    build: 
      context: ./reactapp
      dockerfile: Dockerfile.prod
    container_name: reactmui_prod
    restart: always
    ports:
      - 4173:4173
    networks:
      - web_network

  # Nginx Web Server
  nginx:
    image: nginx:latest
    container_name: nginx_reactmui
    restart: always
    ports:
      - 8800:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - react_prod
    networks:
      - web_network